<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>13.0.0-alpha000</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo Feedback</Title>
    <Description>Feedback module for Umbraco.</Description>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Limbo.Umbraco.Feedback</PackageId>
    <PackageTags>Skybrud, Limbo, Umbraco, Feedback</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/limbo.umbraco.feedback/v1/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/limbo-works/Limbo.Umbraco.Feedback</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/limbo.umbraco.feedback/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/limbo.umbraco.feedback/docs/v13/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Limbo.Umbraco.Feedback" />
    <!--<AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/limbo.umbraco.feedback" />-->
  </ItemGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.58" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[13.0.0,13.999)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[13.0.0,13.999)" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="[13.0.0,13.999)" />
  </ItemGroup>

  <!-- Include package icon for NuGet -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <Content Include="../../LICENSE.md" Pack="false" />
    <Content Include="../../README.md" Pack="false" />
  </ItemGroup>

  <!-- Exclude certain files from the NuGet package -->
  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <None Include="compilerconfig.json" />
    <Content Remove="wwwroot\Styles\Default.less" />
    <None Include="wwwroot\Styles\Default.less" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>