/**
 * Danish localization - ported from `~/wwwroot/Lang/da-DK.xml`. See the note in `en-us.ts`.
 */
export default {
  feedback: {
    statusNew: "Ny",
    statusInprogress: "Igangværende",
    statusInProgress: "Igangværende",
    statusClosed: "Lukket",
    statusNotFound: "Status ikke fundet",
    ratingPositive: "Positiv",
    ratingNegative: "Negativ",
    ratingNotFound: "Bedømmelse ikke fundet",

    labelId: "ID",
    labelSite: "Site",
    labelPage: "Side",
    labelPageId: "Sidens ID",
    labelPageTitle: "Sidens navn",
    labelPageUrl: "URL",
    labelAssignedTo: "Tildelt til",
    labelResponsible: "Ansvarlig",
    labelRating: "Bedømmelse",
    labelName: "Navn",
    labelEmail: "E-mail",
    labelAdded: "Tilføjet",
    labelUpdateDate: "Ændret",
    labelStatus: "Status",
    labelComment: "Kommentar",
    labelNoResponsible: "Ingen ansvarlig",
    labelNotSpecified: "Ikke angivet",
    labelYes: "Ja",
    labelNo: "Nej",
    labelRefresh: "Genindlæs",

    btnArchive: "Arkivér",
    btnDelete: "Slet",
    btnCleaning: "Oprydning",
    btnSelectStatus: "Vælg status",
    btnSelectResponsible: "Vælg ansvarlig",
    btnShowInUmbraco: "Vis i Umbraco",
    btnShowAtWebsite: "Vis på hjemmesiden",

    labelAllRatings: "Alle bedømmelser",
    labelAllUsers: "Alle brugere",
    labelMe: "Mig",
    labelAllStatuses: "Alle statuser",
    labelAllTypes: "Alle typer",
    labelOnlyWithRating: "Kun med bedømmelse",
    labelRatingAndComment: "Bedømmelse og kommentar",

    noEntriesForSite: "Dette site har i øjeblikket ingen feedback-besvarelser.",
    noEntriesForPage: "Denne side har i øjeblikket ingen feedback-besvarelser.",
    noEntriesForFilter: "Din søgning matcher ingen feedback-besvarelser.",
    pageNoLongerExists: "Siden findes ikke længere",
    confirmArchive: "Er du sikker på, at du vil arkivere den valgte besvarelse?",
    confirmDelete: "Er du sikker på, at du vil slette den valgte besvarelse?",
    archiveSuccess: "Besvarelsen blev arkiveret.",
    archiveError: "Besvarelsen kunne ikke arkiveres.",
    deleteSuccess: "Besvarelsen blev slettet.",
    deleteError: "Besvarelsen kunne ikke slettes.",
    loadError: "Feedback-besvarelserne kunne ikke indlæses.",
    saveError: "Besvarelsen kunne ikke gemmes.",
  },
};
